terraform {
    # cloud {
    #     organization = "Customer A"
    #     workspaces {
    #         project = "Supply Chain Indirect Management" 
    #         name = "Compliance Check Scan"
    #     }
    # }
    required_providers {
      aws = {
        source = "hashicorp/aws"
        version = "~> 5.0"
      }
    }
  required_version = ">= 0.12"
}

provider "aws"{
    region = "us-west-2"

    assume_role {
    role_arn     = "arn:aws:iam::264347118673:role/OrganizationAccountAccessRole"
    session_name = "TerraformSession"
  }
}

variable "external_id" {
  type        = string
  description = "Unique secret passphrase generated by the SaaS platform for this tenant"
}

variable "scanning_account_id" {
  type        = string
  description = "The SaaS Provider AWS Account ID"
}

variable "lambda_execution_role_arn" {
  type        = string
  description = "The specific IAM Role ARN used by the SaaS scanning Lambda function"
  default = "arn:aws:iam::123456789012:role/SecurityCheckerLambdaRole"
}




data "aws_iam_policy_document" "instance_assume_role_policy" {
    statement {
        actions = ["sts:AssumeRole"]

        principals {
         type        = "AWS"
         identifiers = ["arn:aws:iam::${var.scanning_account_id}:root"]
         # Restricts access specifically to your Lambda's IAM Execution Role
         # identifiers = [var.lambda_execution_role_arn]
        }
        condition {
             test     = "StringEquals"
             variable = "sts:ExternalId"
             values   = [var.external_id]
    }
  }
}


resource "aws_iam_role" "security_scan_role"{
    name = "security_scan_role"

    # which account and who can assume this role within that account? i.e trusted policy, external id, principle ex: user, roles.
    assume_role_policy = data.aws_iam_policy_document.instance_assume_role_policy.json
    
}

# What this role can do? i.e which custom or aws managed policy is this role attached to access aws resources.
# 2. Separate attachment resource (Terraform best practice)
resource "aws_iam_role_policy_attachment" "security_audit_attach" {
  role       = aws_iam_role.security_scan_role.name
  policy_arn = "arn:aws:iam::aws:policy/SecurityAudit"
}

output "role_arn" {
    value = aws_iam_role.security_scan_role.arn
    description = "Copy and paste this Role ARN into the SaaS application interface"
}


data "aws_caller_identity" "current" {}

output "connected_account_id" {
  value = data.aws_caller_identity.current.account_id
}